# Generated by Django 4.1.7 on 2023-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_goalie', models.BooleanField()),
                ('is_left_full', models.BooleanField()),
                ('is_right_full', models.BooleanField()),
                ('is_center_back', models.BooleanField()),
                ('is_sweeper', models.BooleanField()),
                ('is_stopper', models.BooleanField()),
                ('is_left_mid', models.BooleanField()),
                ('is_right_mid', models.BooleanField()),
                ('is_attacking_mid', models.BooleanField()),
                ('is_left_striker', models.BooleanField()),
                ('is_right_striker', models.BooleanField()),
            ],
        ),
    ]
