# Generated by Django 4.1.7 on 2023-04-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('team_size', models.IntegerField(choices=[(7, '7 vs. 7'), (9, '9 vs. 9'), (11, '11 vs. 11')], default=11)),
                ('team_formation', models.CharField(choices=[('442d', '4-4-2 (diamond)'), ('442f', '4-4-2 (flat)'), ('433', '4-3-3')], default='442d', max_length=4)),
                ('half_duration', models.IntegerField(choices=[(30, '30 minutes'), (35, '35 minutes'), (40, '40 minutes'), (45, '45 minutes')], default=35)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='Lions', max_length=20),
            preserve_default=False,
        ),
    ]
