# Generated by Django 4.1.7 on 2023-04-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_player_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='half_duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('35', '35 minutes'), ('40', '40 minutes'), ('45', '45 minutes')], default='35', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_size',
            field=models.CharField(choices=[('7', '7 vs. 7'), ('9', '9 vs. 9'), ('11', '11 vs. 11')], default='11', max_length=2),
        ),
    ]
