# Generated by Django 4.1.7 on 2023-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='half_duration',
            field=models.CharField(choices=[('35', '35 minutes')], default='35', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_formation',
            field=models.CharField(choices=[('442d', '4-4-2 (diamond)')], default='442d', max_length=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_size',
            field=models.CharField(choices=[('11', '11 vs. 11')], default='11', max_length=2),
        ),
    ]
