# Generated by Django 4.1.7 on 2023-04-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_half_duration_alter_team_team_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='preferred_position',
            field=models.CharField(choices=[('Goalie', 'Goalie'), ('Left_Back', 'Full Back, Left'), ('Left_CB', 'Center Back, Left'), ('Right_CB', 'Center Back, Right'), ('Right_Back', 'Full Back, Right'), ('Left_Mid', 'Left Midfield'), ('Defensive_Mid', 'Defensive Midfielder'), ('Attaching_Mid', 'Attacking Midfielder'), ('Right_Mid', 'Right Midfield'), ('Left_Striker', 'Striker, Left'), ('Right_Striker', 'Striker, Right')], default='goalie', max_length=13),
            preserve_default=False,
        ),
    ]
