# Generated by Django 4.1.7 on 2023-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='opponent',
            field=models.CharField(default='', max_length=20),
        ),
    ]
