# Generated by Django 4.1.7 on 2023-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_alter_lineup_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='number_subs',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineup',
            name='opponent',
            field=models.CharField(default='', max_length=40),
        ),
    ]
