# Generated by Django 4.1.7 on 2023-04-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0004_lineup_first_goalie_lineup_second_goalie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='positions',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
